function love.load () 
  love.window.setMode(1200,1000,{msaa=16})
  love.graphics.setBackgroundColor(1,1,10) 
  love.window.setTitle ("Relógio")
  relogio = love.graphics.newImage("clockface.png")
  ponteiros=love.graphics.newImage("clockhands.png")
  horas=love.graphics.newQuad (45,85,68,167,ponteiros:getWidth(),ponteiros:getHeight())
  min=love.graphics.newQuad(114,15,32,236,ponteiros:getWidth(),ponteiros:getHeight())
  sec=love.graphics.newQuad(163,10,23,350,ponteiros:getWidth(),ponteiros:getHeight())
end
function desenha_relogio () 
  local sx = 600/relogio:getWidth() 
  local sy = 600/relogio:getHeight() 
  love.graphics.setColor(1,1,1) 
  love.graphics.draw(relogio,0,0,0,sx ,sy,relogio:getWidth()/2,relogio:getHeight()/2) 
end
function ponteiro_hora ()
  love.graphics.setColor(1,1,1) 
  love.graphics.draw(ponteiros,horas,0,0,0,1,1,32,152)
end
function ponteiro_min ()
 love.graphics.setColor(1,1,1) 
 love.graphics.draw(ponteiros,min,0,0,0,1,1,16,220)
end
function ponteiro_seg ()
 love.graphics.setColor(1,1,1) 
 love.graphics.draw(ponteiros,sec,0,0,0,1,1,12,227)
end

function love.draw()
  data=os.date("*t")
  love.graphics.translate(love.graphics.getWidth()/2,love.graphics.getHeight()/2)
  desenha_relogio()
  love.graphics.push()
  love.graphics.rotate((data.hour+(data.min/60)+(data.sec/3600))*(math.rad(360/12)))
  ponteiro_hora()
  love.graphics.pop()
  love.graphics.push()
  love.graphics.rotate((data.min+(data.sec/60))*(math.rad(6)))
  ponteiro_min()
  love.graphics.pop()
  love.graphics.push()
  love.graphics.rotate(data.sec*(math.rad(6)))
  ponteiro_seg()
  love.graphics.pop()
end